<?php 
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Filename: " . $nficp.PHP_EOL);
fwrite($swp, "* Contents: Main input data".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Comment area: ".PHP_EOL);
fwrite($swp, "*".PHP_EOL);
fwrite($swp, "* Case: Simulacion del drenaje en la parcela " . $np.PHP_EOL);
fwrite($swp, "* Proyecto LIFE NITRATOS".PHP_EOL);
fwrite($swp, "*".PHP_EOL);
fwrite($swp, "*".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*   The main input file .swp contains the following sections:".PHP_EOL);
fwrite($swp, "*           - General section".PHP_EOL);
fwrite($swp, "*           - Meteorology section".PHP_EOL);
fwrite($swp, "*           - Crop section".PHP_EOL);
fwrite($swp, "*           - Soil water section".PHP_EOL);
fwrite($swp, "*           - Lateral drainage section".PHP_EOL);
fwrite($swp, "*           - Bottom boundary section".PHP_EOL);
fwrite($swp, "*           - Heat flow section".PHP_EOL);
fwrite($swp, "*           - Solute transport section".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** GENERAL SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 1: Environment".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  PROJECT   = " . str_pad("'P-".$np . "'", 20)."! Project description, [A80]".PHP_EOL);
fwrite($swp, "  PATHWORK  = '.\'                ! Path to work folder, [A80]".PHP_EOL);
fwrite($swp, "  PATHATM   = '..\Meteo\'    ! Path to folder with weather files, [A80]".PHP_EOL);
fwrite($swp, "  PATHCROP  = '..\Cultivos\' ! Path to folder with crop files, [A80]".PHP_EOL);
fwrite($swp, "  PATHDRAIN = '.\'     ! Path to folder with drainage files, [A80]".PHP_EOL);
fwrite($swp, "  SWSCRE    = 1                  ! Switch, display progression of simulation run:".PHP_EOL);
fwrite($swp, "                             !   SWSCRE = 0:  no display to screen".PHP_EOL);
fwrite($swp, "                             !   SWSCRE = 1:  display water balance to screen".PHP_EOL);
fwrite($swp, "                             !   SWSCRE = 2:  display daynumber to screen".PHP_EOL);
fwrite($swp, "  SWERROR   = 0              ! Switch for printing errors to screen [Y=1, N=0]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 2: Simulation period".PHP_EOL);
fwrite($swp, "*".PHP_EOL);
fwrite($swp, "  TSTART  = 01-jan-".(1999 +  $yeari)."  ! Start date of simulation run, give day-month-year, [dd-mmm-yyyy]".PHP_EOL);
fwrite($swp, "  TEND    = 31-dec-".(2001 + $y)."  ! End   date of simulation run, give day-month-year, [dd-mmm-yyyy]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 3: Output dates".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Number of output times during a day".PHP_EOL);
fwrite($swp, "  NPRINTDAY = 1       ! Number of output times during a day, [1..1000, I]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If NPRINTDAY = 1, specify dates for output of state variables and fluxes".PHP_EOL);
fwrite($swp, "  SWMONTH = 1         ! Switch, output each month, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWMONTH = 0, choose output interval and/or specific dates".PHP_EOL);
fwrite($swp, "  PERIOD = 0         ! Fixed output interval, ignore = 0, [0..366, I]".PHP_EOL);
fwrite($swp, "  SWRES  = 0          ! Switch, reset output interval counter each year, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "  SWODAT = 0          ! Switch, extra output dates are given in table, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWODAT = 1, list specific dates [dd-mmm-yyyy], maximum MAOUT dates:".PHP_EOL);
fwrite($swp, "  OUTDATINT =".PHP_EOL);
fwrite($swp, "  31-Jan-2007".PHP_EOL);
fwrite($swp, "  31-Dec-1982".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Output times for overall water and solute balances in *.BAL and *.BLC file".PHP_EOL);
fwrite($swp, "* Output can be provided at a fixed date in a year or at different dates:".PHP_EOL);
fwrite($swp, "  SWYRVAR = 0         ! SWYRVAR = 0: each year output of balances at the same date".PHP_EOL);
fwrite($swp, "                      ! SWYRVAR = 1: output of balances at different dates".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWYRVAR = 0 specify fixed date:".PHP_EOL);
fwrite($swp, "  DATEFIX = 31 12     ! Specify day and month for output of yearly balances, [dd mm]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWYRVAR = 1 specify all output dates [dd-mmm-yyyy], maximum MAOUT dates:".PHP_EOL);
fwrite($swp, "  OUTDAT =".PHP_EOL);
fwrite($swp, "  31-dec-1981".PHP_EOL);
fwrite($swp, "  31-dec-1982".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 4: Output files ".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* General information".PHP_EOL);
fwrite($swp, "  OUTFIL   = 'Res_SWAP' ! Generic file name of output files, [A16]".PHP_EOL);
fwrite($swp, "  SWHEADER = 0        ! Print header at the start of each balance period, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Optional files".PHP_EOL);
fwrite($swp, "  SWVAP  = 0        ! Switch, output profiles of moisture, solute and temperature, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "  SWBLC  = 0        ! Switch, output file with detailed yearly water balance, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "  SWATE  = 0        ! Switch, output file with soil temperature profiles, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "  SWBMA  = 0        ! Switch, output file with water fluxes, only for macropore flow, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "  SWDRF  = 0        ! Switch, output of drainage fluxes, only for extended drainage, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "  SWSWB  = 0        ! Switch, output surface water reservoir, only for extended drainage, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Output for water quality models (PEARL, ANIMO) or other specific use (SWAFO to DZNEW)".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Optional output files".PHP_EOL);
fwrite($swp, "  SWAFO  = 0        ! Switch, output file with formatted hydrological data".PHP_EOL);
fwrite($swp, "                   !SWAFO = 0: no output".PHP_EOL);
fwrite($swp, "                    ! SWAFO = 1: output to a file named *.AFO".PHP_EOL);
fwrite($swp, "                    ! SWAFO = 2: output to a file named *.BFO".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWAUN  = 0        ! Switch, output file with unformatted hydrological data".PHP_EOL);
fwrite($swp, "                    !SWAUN = 0: no output".PHP_EOL);
fwrite($swp, "                    ! SWAUN = 1: output to a file named *.AUN".PHP_EOL);
fwrite($swp, "                    ! SWAUN = 2: output to a file named *.BUN".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Critical deviation of water balance; in case of larger deviation, an error file is created (*.DWB.CSV)".PHP_EOL);
fwrite($swp, "  CRITDEVMASBAL = 0.00001  ! Critical Deviation in water balance during PERIOD [0.0..1.0 cm, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWAFO = 1 or 2, or SWAUN = 1 or 2: fine vertical discretization can be lumped".PHP_EOL);
fwrite($swp, "  SWDISCRVERT = 0   ! SWDISCRVERT = 0: no conversion".PHP_EOL);
fwrite($swp, "                    ! SWDISCRVERT = 1: convert vertical discretization,".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWDISCRVERT = 1 then specify:".PHP_EOL);
fwrite($swp, "  NUMNODNEW = 6    ! New number of nodes [1..macp, I, -]".PHP_EOL);
fwrite($swp, "* List thickness of each compartment, total thickness should correspond to Soil Water Section, part 4".PHP_EOL);
fwrite($swp, "  DZNEW     = 10.0 10.0 10.0 20.0 30.0 50.0 ! thickness of compartments [1.0d-6...5.0d2, cm, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** METEOROLOGY SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* General data".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* File name".PHP_EOL);
fwrite($swp, "  METFIL = " . str_pad("'".$estm."'", 12) . " ! File name of meteorological data without extension .YYY, [A200]".PHP_EOL);
fwrite($swp, "                        ! Extension is equal to last 3 digits of year, e.g. 003 denotes year 2003".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Use of reference evapotranspiration data from meteorological file instead of basic data".PHP_EOL);
fwrite($swp, "  SWETR  =  0           ! Switch, use reference ET values of meteo file [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWETR = 0, specify:".PHP_EOL);
fwrite($swp, "  LAT    =    " . $lat . "       ! Latitude of meteo station, [-60..60 degrees, R, North = +]".PHP_EOL);
fwrite($swp, "  ALT    =   " . $alt . "       ! Altitude of meteo station, [-400..3000 m, R]".PHP_EOL);
fwrite($swp, "  ALTW   =   2.0       ! Altitude of wind speed measurement (10 m is default) [0..99 m, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Use of detailed meteorological records for both ET and rainfall (< 1 day) in stead of daily values".PHP_EOL);
fwrite($swp, "  SWMETDETAIL = 0       ! Switch, use detailed meteorological records of both ET and rainfall [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of detailed meteorological weather records (SWMETDETAIL = 1), specify:".PHP_EOL);
fwrite($swp, "  NMETDETAIL = 10       ! Number of weather data records per day, [1..96 -, I]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of daily meteorological weather records (SWMETDETAIL = 0):".PHP_EOL);
fwrite($swp, "  SWETSINE = 0          ! Switch, distribute daily Tp and Ep according to sinus wave [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWRAIN =  0           ! Switch for use of actual rainfall intensity (only if SWMETDETAIL = 0):".PHP_EOL);
fwrite($swp, "                        ! SWRAIN = 0: Use daily rainfall amounts".PHP_EOL);
fwrite($swp, "                        ! SWRAIN = 1: Use daily rainfall amounts + mean intensity".PHP_EOL);
fwrite($swp, "                        ! SWRAIN = 2: Use daily rainfall amounts + duration".PHP_EOL);
fwrite($swp, "                        ! SWRAIN = 3: Use short time rainfall intensities, as supplied in separate file".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWRAIN = 1, then specify mean rainfall intensity RAINFLUX [0.d0..1000.d0 mm/d, R]".PHP_EOL);
fwrite($swp, "* as function of time TIME [0..366 d, R], maximum 30 records".PHP_EOL);
fwrite($swp, "   Time RAINFLUX".PHP_EOL);
fwrite($swp, "    1.0        20.0".PHP_EOL);
fwrite($swp, "  360.0        20.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWRAIN = 3, then specify file name of file with detailed rainfall data".PHP_EOL);
fwrite($swp, "  RAINFIL = 'WagRain'   ! File name of detailed rainfall data without extension .YYY, [A200]".PHP_EOL);
fwrite($swp, "                        ! Extension is equal to last 3 digits of year, e.g. 003 denotes year 2003".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** CROP SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 1: Crop rotation scheme during simulation period".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify information for each crop (maximum MACROP): NOTA 4: Datos del cultivo de cada parcela".PHP_EOL);
fwrite($swp, "* CROPSTART  = date of crop emergence, [dd-mmm-yyyy]".PHP_EOL);
fwrite($swp, "* CROPEND    = date of crop harvest, [dd-mmm-yyyy]".PHP_EOL);
fwrite($swp, "* CROPNAME   = crop name, [A40]".PHP_EOL);
fwrite($swp, "* CROPFIL    = name of file with crop input parameters without extension .CRP, [A40]".PHP_EOL);
fwrite($swp, "* CROPTYPE   = type of crop model: simple = 1, detailed general = 2, detailed grass = 3".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  CROPSTART      CROPEND       CROPNAME   CROPFIL     CROPTYPE".PHP_EOL);
	for ($k = 0; $k <= 2; $k++) // Asigna la misma fecha de siembra y cosecha pero en tres años
	fwrite($swp, " " . $fs[$k] . "    " . $fc[$k] . "   " . str_pad("'".$cropnr."'",12). str_pad("'".$cropnr."'", 15)."1".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 2: Fixed irrigation applications".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch for fixed irrigation applications".PHP_EOL);
fwrite($swp, "  SWIRFIX = 1    ! SWIRFIX = 0: no irrigation applications are prescribed".PHP_EOL);
fwrite($swp, "                 ! SWIRFIX = 1: irrigation applications are prescribed".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWIRFIX = 1, specify:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch for separate file with fixed irrigation applications".PHP_EOL);
fwrite($swp, "  SWIRGFIL  = 1  ! SWIRGFIL = 0: data are specified in the .swp file".PHP_EOL);
fwrite($swp, "                 ! SWIRGFIL = 1: data are specified in a separate file".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWIRGFIL  = 0 specify information for each fixed irrigation event (max. MAIRG):".PHP_EOL);
fwrite($swp, "* IRDATE   = date of irrigation, [dd-mmm-yyyy]".PHP_EOL);
fwrite($swp, "* IRDEPTH  = amount of water, [0.0..100.0 cm, R]".PHP_EOL);
fwrite($swp, "* IRCONC   = concentration of irrigation water, [0.0..1000.0 mg/cm3, R]".PHP_EOL);
fwrite($swp, "* IRTYPE   = type of irrigation: sprinkling = 0, surface = 1".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "       IRDATE        IRDEPTH     IRCONC   IRTYPE".PHP_EOL);
fwrite($swp, "       05-jan-2007       0.5     1000.0        1".PHP_EOL);
fwrite($swp, "* end of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWIRGFIL  = 1, specify name of file with data of fixed irrigation applications:".PHP_EOL);
fwrite($swp, "  IRGFIL = 'riegop'      ! File name without extension .IRG [A16]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** SOIL WATER SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 1: Initial soil moisture condition".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, " SWINCO = 1 ! Switch, type of initial soil moisture condition:".PHP_EOL);
fwrite($swp, "            ! 1 = pressure head as function of depth is input".PHP_EOL);
fwrite($swp, "            ! 2 = pressure head of each compartment is in hydrostatic equilibrium".PHP_EOL);
fwrite($swp, "            !     with initial groundwater level".PHP_EOL);
fwrite($swp, "            ! 3 = read final pressure heads from output of previous Swap simulation".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWINCO = 1, specify (maximum MACP):".PHP_EOL);
fwrite($swp, "* ZI = soil depth, [-10000..0 cm, R]".PHP_EOL);
fwrite($swp, "* H  = initial soil water pressure head, [-1.d10..1.d4 cm, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "      ZI H".PHP_EOL);
fwrite($swp, "    -0.5    -660.0".PHP_EOL);
fwrite($swp, "  -135.0    -660.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWINCO = 2, specify:".PHP_EOL);
fwrite($swp, "  GWLI   = -300.0  ! Initial groundwater level, [-10000..100 cm, R] Se asume a 3 m de profundidad".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWINCO = 3, specify:".PHP_EOL);
fwrite($swp, "  INIFIL = 'result.end'   ! name of final with extension .END [a200]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 2: Ponding, runoff and runon".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Ponding".PHP_EOL);
fwrite($swp, "  PONDMX  = ".$pond."  ! In case of ponding, minimum thickness for runoff, [0..1000 cm, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Runoff".PHP_EOL);
fwrite($swp, "  RSRO    =  0.5 ! Drainage resistance for surface runoff [0.001..1.0 d, R]".PHP_EOL);
fwrite($swp, "  RSROEXP =  1.0 ! Exponent in drainage equation of surface runoff [0.1..10.0 -, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Runon".PHP_EOL);
fwrite($swp, "* Specify whether runon data are provided in extra input file".PHP_EOL);
fwrite($swp, "  SWRUNON = 0  ! 0 = No input of runon data".PHP_EOL);
fwrite($swp, "               ! 1 = Runon data are provided in extra input file".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWRUNON = 1, specify name of file with runon input data".PHP_EOL);
fwrite($swp, "* This file may be an output *.inc file (with only 1 header) of a previous Swap-simulation".PHP_EOL);
fwrite($swp, "  RUFIL = 'runon.inc' ! File name with extension [A80]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 3: Soil evaporation".PHP_EOL);
fwrite($swp, "*".PHP_EOL);
fwrite($swp, "  SWCFBS = 0   ! Switch for use of soil factor CFBS to calculate Epot from ETref".PHP_EOL);
fwrite($swp, "               ! 0 = CFBS is not used".PHP_EOL);
fwrite($swp, "               ! 1 = CFBS is used".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWCFBS = 1, specify soil factor CFBS:".PHP_EOL);
fwrite($swp, "  CFBS   = 1.0 ! Coefficient to derive Epot from ETref [0.1..1.5 -, R]".PHP_EOL);
fwrite($swp, "*".PHP_EOL);
fwrite($swp, "*".PHP_EOL);
fwrite($swp, "  SWREDU = 1   ! Switch, method for reduction of potential soil evaporation:".PHP_EOL);
fwrite($swp, "               ! 0 = reduction to maximum Darcy flux".PHP_EOL);
fwrite($swp, "               ! 1 = reduction to maximum Darcy flux and to maximum Black (1969)".PHP_EOL);
fwrite($swp, "               ! 2 = reduction to maximum Darcy flux and to maximum Bo/Str. (1986)".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, " COFRED = 0.35 ! Soil evaporation coefficient of Black, [0..1 cm/d1/2, R],".PHP_EOL);
fwrite($swp, "               ! or Boesten/Stroosnijder, [0..1 cm1/2, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, " RSIGNI =  0.5 ! Minimum rainfall to reset method of Black [0..1 cm/d, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 4: Vertical discretization of soil profile".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify the following data (maximum MACP lines):".PHP_EOL);
fwrite($swp, "* ISOILLAY = number of soil layer, start with 1 at soil surface, [1..MAHO, I]".PHP_EOL);
fwrite($swp, "* ISUBLAY  = number of sub layer, start with 1 at soil surface, [1..MACP, I]".PHP_EOL);
fwrite($swp, "* HSUBLAY  = height of sub layer, [0.0..1000.0 cm, R]".PHP_EOL);
fwrite($swp, "* HCOMP    = height of compartments in this layer, [0.0..1000.0 cm, R]".PHP_EOL);
fwrite($swp, "* NCOMP    = number of compartments in this layer (= HSUBLAY/HCOMP), [1..MACP, I]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, " ISOILLAY ISUBLAY  HSUBLAY    HCOMP    NCOMP".PHP_EOL);
fwrite($swp, "     1       1       10.0      1.0       10".PHP_EOL);
fwrite($swp, "     1       2       20.0      5.0        4".PHP_EOL);
fwrite($swp, "     2       3       30.0      5.0        6".PHP_EOL);
fwrite($swp, "     2       4      140.0     10.0       14".PHP_EOL);
fwrite($swp, "* end of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 5: Soil hydraulic functions".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch for Mualem - van Genuchten parameters or detailed tabels:".PHP_EOL);
fwrite($swp, "  SWSOPHY = 0   ! 0 = Mualem - van Genuchten parameters".PHP_EOL);
fwrite($swp, "                ! 1 = Detailed tables".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWSOPHY = 0, specify for each soil layer (maximum MAHO):".PHP_EOL);
fwrite($swp, "* ISOILLAY1 = number of soil layer, as defined in part 4 [1..MAHO, I]".PHP_EOL);
fwrite($swp, "* ORES   = Residual water content, [0..0.4 cm3/cm3, R]".PHP_EOL);
fwrite($swp, "* OSAT   = Saturated water content, [0..0.95 cm3/cm3, R]".PHP_EOL);
fwrite($swp, "* ALFA   = Shape parameter alfa of main drying curve, [0.0001..1 /cm, R]".PHP_EOL);
fwrite($swp, "* NPAR   = Shape parameter n, [1..4 -, R]".PHP_EOL);
fwrite($swp, "* KSAT   = Saturated vertical hydraulic conductivity, [1.d-5..1000 cm/d, R]".PHP_EOL);
fwrite($swp, "* LEXP   = Exponent in hydraulic conductivity function, [-25..25 -, R]".PHP_EOL);
fwrite($swp, "* ALFAW  = Alfa parameter of main wetting curve in case of hysteresis, [0.0001..1 /cm, R]".PHP_EOL);
fwrite($swp, "* H_ENPR = Air entry pressure head [-40.0..0.0 cm, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  ISOILLAY1  ORES    OSAT      ALFA    NPAR     KSAT      LEXP    ALFAW H_ENPR  KSATEXM".PHP_EOL);
fwrite($swp, $proph1.PHP_EOL);
fwrite($swp, $proph2.PHP_EOL);
fwrite($swp, "* --- end of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWSOPHY = 1, specify names of input files [A80] with soil hydraulic tables for each soil layer:".PHP_EOL);
fwrite($swp, "  FILENAMESOPHY = 'topsoil_sand_B2.csv', 'subsoil_sand_O2.csv'".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 6: Hysteresis of soil water retention function".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch for hysteresis:".PHP_EOL);
fwrite($swp, "  SWHYST = 0   ! 0 = no hysteresis".PHP_EOL);
fwrite($swp, "               ! 1 = hysteresis, initial condition wetting".PHP_EOL);
fwrite($swp, "               ! 2 = hysteresis, initial condition drying".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWHYST = 1 or 2, specify:".PHP_EOL);
fwrite($swp, " TAU = 0.2    ! Minimum pressure head difference to change wetting-drying, [0..1 cm, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 7: Maximum rooting depth".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  RDS  = 150.0   ! Maximum rooting depth allowed by the soil profile, [1..5000 cm, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 8: Similar media scaling of soil hydraulic functions".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWSCAL = 0 ! Switch for similar media scaling [Y=1, N=0]; no hysteresis is allowed".PHP_EOL);
fwrite($swp, "             ! in case of similar media scaling (SWHYST = 0)".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWSCAL = 1, specify:".PHP_EOL);
fwrite($swp, "  NSCALE = 3 ! Number of simulation runs, [1..MASCALE, I]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Supply the scaling factors for each simulation run and each soil layer:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  RUN     SOIL1        SOIL2".PHP_EOL);
fwrite($swp, "   1       0.5          2.0".PHP_EOL);
fwrite($swp, "   2       1.0          1.0".PHP_EOL);
fwrite($swp, "   3       2.0          0.5".PHP_EOL);
fwrite($swp, "   4       1.0          1.0".PHP_EOL);
fwrite($swp, "   5       3.0          3.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 9: Preferential flow due to macropores".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWMACRO = 0     ! Switch for macropore flow, [0..2, I]:".PHP_EOL);
fwrite($swp, "                  ! 0 = no macropore flow".PHP_EOL);
fwrite($swp, "                  ! 1 = macropore flow".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 10: Snow and frost".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Snow".PHP_EOL);
fwrite($swp, "  SWSNOW = 0   ! Switch, calculate snow accumulation and melt, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWSNOW = 1, specify:".PHP_EOL);
fwrite($swp, "  SNOWINCO = 22.0      ! Initial snow water equivalent, [0.0...1000.0 cm, R]".PHP_EOL);
fwrite($swp, "  TEPRRAIN = 2.0       ! Temperature above which all precipitation is rain,[ 0.0...5.0 ºC, R]".PHP_EOL);
fwrite($swp, "  TEPRSNOW = -2.0      ! Temperature below which all precipitation is snow,[-5.0...0.0 ºC, R]".PHP_EOL);
fwrite($swp, "  SNOWCOEF = 0.3       ! Snowmelt calibration factor, [0.0...10.0 -, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Frost".PHP_EOL);
fwrite($swp, "  SWFROST = 0  ! Switch, in case of frost: reduce soil water flow, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWFROST = 1, then specify soil temperature to start end end flux-reduction".PHP_EOL);
fwrite($swp, "  tfroststa = 0.0      ! Soil temperature (ºC) where reduction of water fluxes starts [-10.0,5.0, oC, R]".PHP_EOL);
fwrite($swp, "  tfrostend = -1.0     ! Soil temperature (ºC) where reduction of water fluxes ends [-10.0,5.0, oC, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 11 Numerical solution of Richards' equation".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  DTMIN         = 1.0d-6     ! Minimum timestep, [1.d-7..0.01 d, R]".PHP_EOL);
fwrite($swp, "  DTMAX         = 0.2        ! Maximum timestep, [ 0.01..0.5 d, R]".PHP_EOL);
fwrite($swp, "  GWLCONV       = 100.0      ! Maximum dif. groundwater level between iterations, [1.d-5..1000 cm, R]".PHP_EOL);
fwrite($swp, "  CritDevh1Cp   = 1.0d-2     ! Maximum relative difference in pressure heads per compartment, [1.0d-10..0.1 -, R]".PHP_EOL);
fwrite($swp, "  CritDevh2Cp   = 1.0d-1     ! Maximum difference in pressure heads per compartment, [1.0d-10..1.0 cm, R]".PHP_EOL);
fwrite($swp, "  CritDevPondDt = 1.0d-4     ! Maximum water balance error of ponding layer, [1.0d-6..0.1 cm, R]".PHP_EOL);
fwrite($swp, "  MaxIt         = 30         ! Maximum number of iteration cycles, [5..100 -, I]".PHP_EOL);
fwrite($swp, "  MaxBackTr     = 3          ! Maximum number of back track cycles within an iteration cycle, [1..10 -,I]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch for mean of hydraulic conductivity, [1..4 -, I]:".PHP_EOL);
fwrite($swp, "* 1 = unweighted  arithmic mean; 2 = weighted  arithmic mean".PHP_EOL);
fwrite($swp, "* 3 = unweighted geometric mean; 4 = weighted geometric mean".PHP_EOL);
fwrite($swp, "  SWkmean = 1".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch for explicit/implicit solution Richards equation with hydraulic conductivity, [1..2 -, I]:".PHP_EOL);
fwrite($swp, "  SWkImpl = 0   ! 0 = explicit solution".PHP_EOL);
fwrite($swp, "                ! 1 = implicit solution".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** LATERAL DRAINAGE SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Specify whether lateral drainage to surface water should be included".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWDRA = 0  ! Switch, simulation of lateral drainage:".PHP_EOL);
fwrite($swp, "             ! 0 = No simulation of drainage".PHP_EOL);
fwrite($swp, "             ! 1 = Simulation with basic drainage routine".PHP_EOL);
fwrite($swp, "             ! 2 = Simulation of drainage with surface water management".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWDRA = 1 or SWDRA = 2 specify name of file with drainage input data:".PHP_EOL);
fwrite($swp, "  DRFIL = 'Hupsel' ! File name with drainage input data without extension .DRA, [A16]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** BOTTOM BOUNDARY SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Bottom boundary condition".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWBBCFILE  = 0    ! Switch for file with bottom boundary conditions:".PHP_EOL);
fwrite($swp, "                    ! SWBBCFILE = 0: data are specified in the .swp file".PHP_EOL);
fwrite($swp, "                    ! SWBBCFILE = 1: data are specified in a separate file".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWBBCFILE = 1 specify name of file with bottom boundary conditions:".PHP_EOL);
fwrite($swp, "  BBCFIL = ' '      ! File name without extension .BBC [A16]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWBBCFILE = 0, select one of the following options:".PHP_EOL);
fwrite($swp, "             ! 1  Prescribe groundwater level".PHP_EOL);
fwrite($swp, "             ! 2  Prescribe bottom flux".PHP_EOL);
fwrite($swp, "             ! 3  Calculate bottom flux from hydraulic head of deep aquifer".PHP_EOL);
fwrite($swp, "             ! 4  Calculate bottom flux as function of groundwater level".PHP_EOL);
fwrite($swp, "             ! 5  Prescribe soil water pressure head of bottom compartment".PHP_EOL);
fwrite($swp, "             ! 6  Bottom flux equals zero".PHP_EOL);
fwrite($swp, "             ! 7  Free drainage of soil profile".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, " SWBOTB = 7  ! Switch for bottom boundary [1..8,-,I]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Options 6,7 and 8 require no additional bottom input data".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* SWBOTB = 1  Prescribe groundwater level".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* specify DATE [dd-mmm-yyyy] and groundwater level [cm, -10000..1000, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "        DATE1    GWLEVEL         ! (max. MABBC records)".PHP_EOL);
fwrite($swp, "  01-jan-1981     -95.0".PHP_EOL);
fwrite($swp, "  31-dec-1983     -95.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* SWBOTB = 2   Prescribe bottom flux".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify whether a sine or a table are used to prescribe the bottom flux:".PHP_EOL);
fwrite($swp, "  SW2    = 2      ! 1 = sine function; 2 = table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of sine function (SW2 = 1), specify:".PHP_EOL);
fwrite($swp, "  SINAVE =  0.1   ! Average value of bottom flux, [-10..10 cm/d, R, + = upwards]".PHP_EOL);
fwrite($swp, "  SINAMP =  0.05  ! Amplitude of bottom flux sine function, [-10..10 cm/d, R]".PHP_EOL);
fwrite($swp, "  SINMAX =  91.0  ! Time of the year with maximum bottom flux, [1..366 d, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of table (SW2 = 2), specify date [dd-mmm-yyyy] and bottom flux QBOT2".PHP_EOL);
fwrite($swp, "* [-100..100 cm/d, R, positive = upwards]:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "        DATE2     QBOT2           ! (maximum MABBC records)".PHP_EOL);
fwrite($swp, "  01-jan-2007       0.1".PHP_EOL);
fwrite($swp, "  30-jun-2007       0.2".PHP_EOL);
fwrite($swp, "  23-dec-2007      0.15".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* SWBOTB = 3    Calculate bottom flux from hydraulic head in deep aquifer".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch to suppress vertical hydraulic resistance between model bottom and groundwater level".PHP_EOL);
fwrite($swp, "  SWBOTB3RESVERT = 0 ! 0 = Include vertical hydraulic resistance".PHP_EOL);
fwrite($swp, "                     ! 1 = Suppress vertical hydraulic resistance".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Switch for numerical solution of bottom flux: 0 = explicit, 1 = implicit".PHP_EOL);
fwrite($swp, "  SWBOTB3IMPL = 0    ! 0 = explicit solution (choose always when SHAPE < 1.0)".PHP_EOL);
fwrite($swp, "                     ! 1 = implicit solution".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify:".PHP_EOL);
fwrite($swp, "  SHAPE  =   0.79  ! Shape factor to derive average groundwater level, [0.0..1.0 -, R]".PHP_EOL);
fwrite($swp, "  HDRAIN =  -110.0 ! Mean drain base to correct for average groundwater level, [-10000..0 cm, R]".PHP_EOL);
fwrite($swp, "  RIMLAY =   500.0 ! Vertical resistance of aquitard, [0..10000 d, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify whether a sine function or a table are used to prescribe hydraulic head of deep aquifer:".PHP_EOL);
fwrite($swp, "  SW3    = 1       ! 1 = sine function;  2 = table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of sine function (SW3  = 1), specify:".PHP_EOL);
fwrite($swp, "  AQAVE  =  -140.0 ! Average hydraulic head in underlaying aquifer, [-10000..1000 cm, R]".PHP_EOL);
fwrite($swp, "  AQAMP  =    20.0 ! Amplitude hydraulic head sinus wave, [0..1000 cm, R]".PHP_EOL);
fwrite($swp, "  AQTMAX =  120.0  ! First time of the year with maximum hydraulic head, [1..366 d, R]".PHP_EOL);
fwrite($swp, "  AQPER  =  365.0  ! Period hydraulic head sinus wave, [1..366 d, I]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of table (SW3  = 2), specify date [dd-mmm-yyyy] and average hydraulic head".PHP_EOL);
fwrite($swp, "* HAQUIF in underlaying aquifer [-10000..1000 cm, R]:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "        DATE3    HAQUIF           ! (maximum MABBC records)".PHP_EOL);
fwrite($swp, "  01-jan-2007     -95.0".PHP_EOL);
fwrite($swp, "  30-jun-2007    -110.0".PHP_EOL);
fwrite($swp, "  23-dec-2007     -70.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* An extra groundwater flux can be specified which is added to above specified flux".PHP_EOL);
fwrite($swp, "  SW4   = 1        ! 0 = no extra flux; 1 = include extra flux".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SW4 = 1, specify date [dd-mmm-yyyy] and bottom flux QBOT4 [-100..100 cm/d, R,".PHP_EOL);
fwrite($swp, "* positive = upwards]:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "        DATE4     QBOT4           ! (maximum MABBC records)".PHP_EOL);
fwrite($swp, "  01-jan-2007       1.0".PHP_EOL);
fwrite($swp, "  30-jun-2007     -0.15".PHP_EOL);
fwrite($swp, "  23-dec-2007       1.2".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* SWBOTB = 4     Calculate bottom flux as function of groundwater level".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify whether an exponential relation or a table is used to calculate the bottom flux".PHP_EOL);
fwrite($swp, "* from the groundwater level:".PHP_EOL);
fwrite($swp, "  SWQHBOT = 2       ! 1 = exponential relation;  2 = table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of an exponential relation (SWQHBOT  = 1),".PHP_EOL);
fwrite($swp, "* specify coefficients of relation qbot = A exp (B*abs(groundwater level))".PHP_EOL);
fwrite($swp, "  COFQHA =  0.1  ! Coefficient A, [-100..100 cm/d, R]".PHP_EOL);
fwrite($swp, "  COFQHB =  0.5  ! Coefficient B  [-1..1 /cm, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of a table (SWQHBOT  = 2),".PHP_EOL);
fwrite($swp, "* specify groundwaterlevel Htab [-10000..1000, cm, R]  and bottom flux QTAB [-100..100 cm/d, R]".PHP_EOL);
fwrite($swp, "* Htab is negative below the soil surface, Qtab is negative when flux is downward.".PHP_EOL);
fwrite($swp, "  HTAB QTAB".PHP_EOL);
fwrite($swp, "  -0.1   -0.35".PHP_EOL);
fwrite($swp, "  -70.0  -0.05".PHP_EOL);
fwrite($swp, " -125.0  -0.01".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* SWBOTB = 5     Prescribe soil water pressure head of bottom compartment".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify DATE [dd-mmm-yyyy] and bottom compartment pressure head HBOT5 [-1.d10..1000 cm, R]:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "        DATE5     HBOT5           ! (maximum MABBC records)".PHP_EOL);
fwrite($swp, "  01-jan-2007     -95.0".PHP_EOL);
fwrite($swp, "  30-jun-2007    -110.0".PHP_EOL);
fwrite($swp, "  23-dec-2007     -70.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** HEAT FLOW SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 1: Specify whether simulation includes heat flow".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWHEA  = 0 ! Switch for simulation of heat transport, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 2: Heat flow calculation method".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWCALT = 2     ! Switch for method: 1 = analytical method, 2 = numerical method".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 3: Analytical method".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWCALT = 1 specify the following heat parameters:".PHP_EOL);
fwrite($swp, "  TAMPLI = 10.0 ! Amplitude of annual temperature wave at soil surface, [0..50 C, R]".PHP_EOL);
fwrite($swp, "  TMEAN  = 15.0 ! Mean annual temperature at soil surface, [5..30 C, R]".PHP_EOL);
fwrite($swp, "  TIMREF = 90.0 ! Time in the year with top of sine temperature wave [1..366 d, R]".PHP_EOL);
fwrite($swp, "  DDAMP  = 50.0 ! Damping depth of temperature wave in soil, [0..500 cm, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 4: Numerical method".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWCALT = 2 specify the following heat parameters:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify for each soil type the soil texture (g/g mineral parts)".PHP_EOL);
fwrite($swp, "* and the organic matter content (g/g dry soil):".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  ISOILLAY5  PSAND    PSILT    PCLAY    ORGMAT           ! (maximum MAHO records)".PHP_EOL);
fwrite($swp, "     1        0.80     0.15     0.05     0.100".PHP_EOL);
fwrite($swp, "     2        0.80     0.15     0.05     0.100".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWINCO = 1 or 2, list initial temperature TSOIL [-20..40 C, R] as function of".PHP_EOL);
fwrite($swp, "* soil depth ZH [-1.0d5..0 cm, R]:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "      ZH    TSOIL   ! (maximum MACP records)".PHP_EOL);
fwrite($swp, "   -10.0     15.0".PHP_EOL);
fwrite($swp, "   -40.0     12.0".PHP_EOL);
fwrite($swp, "   -70.0     10.0".PHP_EOL);
fwrite($swp, "   -95.0      9.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Define top boundary condition:".PHP_EOL);
fwrite($swp, "  SwTopbHea = 1     ! 1 = use air temperature of meteo input file as top boundary".PHP_EOL);
fwrite($swp, "                    ! 2 = use measured top soil temperature as top boundary".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SwTopbHea = 2, specify name of input file with soil surface temperatures".PHP_EOL);
fwrite($swp, "  TSOILFILE = 'Haarweg' ! File name without extension .TSS, [A16]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Define bottom boundary condition:".PHP_EOL);
fwrite($swp, "  SwBotbHea = 1     ! 1 = no heat flux; 2 = prescribe bottom temperature".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SwBotbHea = 2, specify a tabel with dates and temperatures at bottom boundary".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  DATET           TBOT   ! (maximum MABBC records)".PHP_EOL);
fwrite($swp, "  01-jan-2007    -15.0".PHP_EOL);
fwrite($swp, "  30-jun-2007    -20.0".PHP_EOL);
fwrite($swp, "  23-dec-2007    -10.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "*** SOLUTE SECTION ***".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 1: Specify whether simulation includes solute transport".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWSOLU = 0 ! Switch for simulation of solute transport, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 2: Top boundary and initial condition".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  CPRE = 0.0    ! Solute concentration in precipitation, [1..100 mg/cm3, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* If SWINCO = 1 or 2, list initial solute concentration CML [1..1000 mg/cm3, R]".PHP_EOL);
fwrite($swp, "* as function of soil depth ZC [-10000..0 cm, R], max. MACP records:".PHP_EOL);
fwrite($swp, "      ZC CML".PHP_EOL);
fwrite($swp, "   -10.0       0.0".PHP_EOL);
fwrite($swp, "   -95.0       0.0".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 3: Miscellaneous parameters as function of soil depth".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Specify for each soil layer (maximum MAHO)".PHP_EOL);
fwrite($swp, "* ISOILLAY6 = number of soil layer, as defined in soil water section (part 4) [1..MAHO, I]".PHP_EOL);
fwrite($swp, "* LDIS      = dispersion length, [0..100 cm, R]".PHP_EOL);
fwrite($swp, "* KF        = Freundlich adsorption coefficient, [0..100 cm3/mg, R]".PHP_EOL);
fwrite($swp, "* BDENS     = dry soil bulk density, [500..3000 mg/cm3, R]".PHP_EOL);
fwrite($swp, "* DECPOT    = potential decomposition rate, [0..10 /d, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, " ISOILLAY6     LDIS          KF     BDENS  DECPOT".PHP_EOL);
fwrite($swp, "     1         5.00   0.0001389   1315.00     0.0".PHP_EOL);
fwrite($swp, "     2         5.00   0.0001378   1318.00     0.0".PHP_EOL);
fwrite($swp, "* --- end of Table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 4: Diffusion constant and solute uptake by roots".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  DDIF = 0.0    ! Molecular diffusion coefficient, [0..10 cm2/day, R]".PHP_EOL);
fwrite($swp, "  TSCF = 0.0    ! Relative uptake of solutes by roots, [0..10 -, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 5: Adsorption".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWSP = 0      ! Switch, consider solute adsorption, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of adsorption (SWSP = 1), specify:".PHP_EOL);
fwrite($swp, "  FREXP = 0.9   ! Freundlich exponent, [0..10 -, R]".PHP_EOL);
fwrite($swp, "  CREF  = 1.0   ! Reference solute concentration for adsorption, [0..1000 mg/cm3, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 6: Decomposition".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWDC = 0      ! Switch, consideration of solute decomposition, [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of solute decomposition (SWDC = 1), specify:".PHP_EOL);
fwrite($swp, "  GAMPAR = 0.0  ! Factor reduction decomposition due to temperature, [0..0.5 /ºC, R]".PHP_EOL);
fwrite($swp, "  RTHETA = 0.3  ! Minimum water content for potential decomposition, [0..0.4 cm3/cm3, R]".PHP_EOL);
fwrite($swp, "  BEXP   = 0.7  ! Exponent in reduction decomposition due to dryness, [0..2 -, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* List the reduction of pot. decomposition for each soil type, [0..1 -, R]:".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  ISOILLAY7  FDEPTH           ! (maximum MAHO records)".PHP_EOL);
fwrite($swp, "       1       1.00".PHP_EOL);
fwrite($swp, "       2       0.65".PHP_EOL);
fwrite($swp, "* End of table".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "* Part 7: Solute residence in the saturated zone".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "  SWBR = 0       ! Switch, consider mixed reservoir of saturated zone [Y=1, N=0]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* Without mixed reservoir (SWBR = 0), specify:".PHP_EOL);
fwrite($swp, "  CDRAIN = 0.1   ! solute concentration in groundwater, [0..100 mg/cm3, R]".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* In case of mixed reservoir (SWBR = 1), specify:".PHP_EOL);
fwrite($swp, "  DAQUIF = 110.0 ! Thickness saturated part of aquifer, [0..10000 cm, R]".PHP_EOL);
fwrite($swp, "  POROS  = 0.4   ! Porosity of aquifer, [0..0.6 -, R]".PHP_EOL);
fwrite($swp, "  KFSAT  = 0.2   ! Linear adsorption coefficient in aquifer, [0..100 cm3/mg, R]".PHP_EOL);
fwrite($swp, "  DECSAT = 1.0   ! Decomposition rate in aquifer, [0..10 /d, R]".PHP_EOL);
fwrite($swp, "  CDRAINI = 0.2  ! Initial solute concentration in groundwater, [0..100 mg/cm3, R]".PHP_EOL);
fwrite($swp, "**********************************************************************************".PHP_EOL);
fwrite($swp, "".PHP_EOL);
fwrite($swp, "* End of the main input file .SWP!".PHP_EOL);


?>
