Vue.component('wws', {
    props: {
        wep: String
    },
    data() {
        return {
            ws: ''
             }
    },
    created() {
        var we = [
            'Sandstorm',
            'Thunderstorms',
            'Hail',
            'Blowing Snow',
            'Snow Showers',
            'Snow',
            'Light Snow',
            'Sleet',
            'Showers',
            'Occasional Showers',
            'Isolated Showers',
            'Light Showers',
            'Freezing Rain',
            'Rain',
            'Drizzle',
            'Fog',
            'Mist',
            'Smoke',
            'Haze',
            'Overcast',
            'Sunny Intervals',
            'Sunny Periods',
            'Cloudy',
            'Bright',
            'Windy',
            'Wet',
            'Dry',
            'Freezing',
            'Frost',
            'Hot',
            'Cold',
            'Warm',
            'Cool',
            'Volcanic Ash',
            'Duststorm',
            'Thundershowers',
            'Blizzard',
            'Flurries',
            'Heavy Snow',
            'Heavy Showers',
            'Scattered Showers',
            'Light Rain',
            'No Rain',
            'Partly Cloudy',
            'Mostly Cloudy',
            'Sunny',
            'Squall',
            'Humid',
            'Chilly',
            'Sand',
            'Storm',
            'Snowdrift',
            'Snowfall',
            'Rainshower',
            'Clearing',
            'Partly Bright',
            'Fair',
            'Stormy',
            'Dust',
            'Lightning',
            'Snowstorm',
            'Clear' ];
    var ws = [
        'Tormenta de arena',
        'Tormentas',
        'Granizo',
        'Nevada',
        'Nevadas',
        'Nieve',
        'Nieve ligera',
        'Aguanieve',
        'Chubascos',
        'Chubascos ocasionales',
        'Chubascos aislados',
        'Ligeros chubascos',
        'Lluvia helada',
        'Lluvia',
        'Llovizna',
        'Niebla',
        'Niebla',
        'Humareda',
        'Calima',
        'Nublado',
        'Intervalos soleados',
        'Períodos soleados',
        'Nublado',
        'Soleado',
        'Ventoso',
        'Húmedo',
        'Seco',
        'Congelación',
        'escarcha',
        'Caliente',
        'Frío',
        'Caluroso',
        'Frio',
        'Ceniza volcánica',
        'Tormenta de arena',
        'Lluvias',
        'Tormenta de nieve',
        'Ráfagas',
        'Fuertes nevadas',
        'Aguaceros',
        'Chubascos dispersos',
        'Lluvia ligera',
        'Sin lluvia',
        'Parcialmente nublado',
        'Mayormente nublado',
        'Soleado',
        'Chubasco',
        'Húmedo',
        'Frío',
        'Arena',
        'Tormenta',
        'Ventisquero',
        'Nevada',
        'Aguacero',
        'Claro',
        'Parcialmente soleado',
        'Justa',
        'Tormentoso',
        'Polvo',
        'Relámpagos',
        'Nevada',
        'Despejado'
            ];
        var indc = we.indexOf(this.wep);
        this.ws = ws[indc]; 
    },
    template: `
    <span>{{ws}}</span>`
})
